name: child_safety_monitor
description: A Flutter app to monitor child safety in vehicles using ESP32

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  intl: ^0.18.1
  flutter_local_notifications: ^16.3.2
  google_fonts: ^6.1.0
  firebase_core: ^2.32.0
  firebase_database: ^10.5.7
  firebase_database_web: ^0.2.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
