name: child_safety_monitor
description: A Flutter app to monitor child safety in vehicles using ESP32

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.1.1
  flutter_screenutil: ^5.9.0
  flutter_local_notifications: ^17.2.4
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  firebase_database: ^10.5.7
  firebase_database_web: ^0.2.1+2
  firebase_auth: ^4.20.0
  firebase_auth_web: ^5.12.0
  firebase_messaging: ^14.7.10
  firebase_messaging_web: ^3.5.7
  firebase_messaging_platform_interface: ^4.5.3
  google_sign_in: ^6.3.0
  google_sign_in_web: ^0.12.4+4
  url_launcher: ^6.2.5
  flutter_animate: ^4.2.0
  connectivity_plus: ^6.1.5
  shared_preferences: ^2.2.2
  timezone: ^0.9.4 # For timezone support in notifications
  intl: ^0.20.2 # For date/time formatting
  flutter_local_notifications_linux: ^4.0.0
  flutter_local_notifications_platform_interface: ^7.1.2
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Add assets
  assets:
    - assets/images/google_logo.png
    - .env
