// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6V4YX8qABZEt3Hm_zS89frxUnSJ55pIM',
    appId: '1:217976487619:web:71c35d59ee11f17ac22c76',
    messagingSenderId: '217976487619',
    projectId: 'child-monitering-system',
    authDomain: 'child-monitering-system.firebaseapp.com',
    storageBucket: 'child-monitering-system.firebasestorage.app',
    measurementId: 'G-0JPZ16DQSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBrX3o9CpLbtAYJC-8B5t8rUhiQKIiplk',
    appId: '1:217976487619:android:76ace1b7cf119209c22c76',
    messagingSenderId: '217976487619',
    projectId: 'child-monitering-system',
    storageBucket: 'child-monitering-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp35tpC3q5As6_gyvn6jaQMWa1n59QT-Y',
    appId: '1:217976487619:ios:9de8f23dbf83a18dc22c76',
    messagingSenderId: '217976487619',
    projectId: 'child-monitering-system',
    storageBucket: 'child-monitering-system.firebasestorage.app',
    iosBundleId: 'com.example.childSafetyMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp35tpC3q5As6_gyvn6jaQMWa1n59QT-Y',
    appId: '1:217976487619:ios:9de8f23dbf83a18dc22c76',
    messagingSenderId: '217976487619',
    projectId: 'child-monitering-system',
    storageBucket: 'child-monitering-system.firebasestorage.app',
    iosBundleId: 'com.example.childSafetyMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6V4YX8qABZEt3Hm_zS89frxUnSJ55pIM',
    appId: '1:217976487619:web:a8257a7bfbc908dec22c76',
    messagingSenderId: '217976487619',
    projectId: 'child-monitering-system',
    authDomain: 'child-monitering-system.firebaseapp.com',
    storageBucket: 'child-monitering-system.firebasestorage.app',
    measurementId: 'G-JGP17RBV3E',
  );
}
